export const getRandomQuote = () => quotes[Math.floor(Math.random() * quotes.length)];

export const quotes = [
  'A bad worker blames his tools.',
  'A fall into a ditch makes you wiser.',
  'A goal is a dream with a deadline.',
  'A journey of a thousand miles begins with a single step.',
  'A person must be big enough to admit his mistakes, smart enough to profit from them, and strong enough to correct them.',
  'A ship in harbor is safe, but that\'s not what ships are built for.',
  'A successful person is one who can lay a firm foundation with the bricks others have thrown at him.',
  'Action may not always bring happiness, but there is no happiness without action.',
  'All cats love fish but fear to wet their paws.',
  'Anything the mind can conceive and believe, it can achieve.',
  'Arriving at one goal is the starting point to another.',
  'As long as you\'re going to be thinking anyway, think big.',
  'Assume you have 90 seconds with a new user before they decide to use your app or delete it.',
  'Believe that you will succeed.',
  'Business success requires training and discipline, and hard work. But if you\'re not frightened by these things, the opportunities are just as great today as they ever were.',
  'Careful thinking and hard work will solve nearly all your problems. Try and see for yourself.',
  'Commitment leads to action. Action brings your dream closer.',
  'Do not anticipate trouble or worry about what may never happen. Keep in the sunlight.',
  'Even if you don\'t have a perfect idea to begin with, you can likely adapt.',
  'Every artist was first an amateur.',
  'Every feature has some maintenance cost, and having fewer features lets us focus on the ones we care about and make sure they work very well.',
  'Everyone is a genius, but if you judge a fish by its ability to climb a tree, it will spend its whole life believing it is stupid.',
  'Fail often so you can succeed sooner.',
  'Failure defeats losers; failure inspires winners.',
  'Failure is just another way to learn how to do something right.',
  'Fall seven times and stand up eight.',
  'Find a job you love, and you\'ll never work a day in your life.',
  'Formal education will make you a living; self-education will make you a fortune.',
  'Go confidently in the direction of your dreams. Live the life you have imagined.',
  'Happiness is not a goal but a by-product.',
  'Happiness is not a state to arrive at but a manner of traveling.',
  'I cannot give you the formula for success, but I can give you the recipe for failure.',
  'I failed my way to success.',
  'I have not failed. I\'ve just found 10,000 ways that won\'t work.',
  'If you aren\'t making waves, you aren\'t kickin\' hard enough.',
  'If you cannot do great things, do small things in a great way.',
  'In between goals is a thing called life, that has to be lived and enjoyed.',
  'It \'s nice to be important, but more important to be nice.',
  'It is never too late to be what you might have been.',
  'It would be best if you didn\'t focus on why you can\'t do something which most people do. It would help if you concentrate on why perhaps you can, and be one of the exceptions.',
  'It\'s easier to ask forgiveness than it is to get permission.',
  'It\'s OK to celebrate success, but it is more important to heed the lessons of failure.',
  'Keep ongoing, and the chances are that you will stumble on something, perhaps when you are least expecting it. I never heard of anyone ever struggling on something sitting down.',
  'Leaders don\'t force people to follow; they invite them on a journey.',
  'Leadership is doing what is right when no one is watching.',
  'Live in each season as it passes; breathes the air, drink the drink, tastes the fruit, and resign yourself to the influences of each.',
  'Make your team feel respected, empowered, and genuinely excited about the company\'s mission.',
  'Most \'impossible\' goals can be met simply by breaking them down into bite-size chunks, writing them down, believing them, and then going full speed ahead as if they were routine.',
  'Most great people have attained their most tremendous success, just one step beyond their greatest failure.',
  'My number one piece of advice is: you should learn how to program.',
  'No person was ever wise by chance.',
  'One day your life will flash before your eyes. Make sure it is worth watching.',
  'Only those who dare to fail greatly can ever achieve greatly.',
  'Openly share and talk to people about your idea. Use their lack of interest or doubt to fuel your motivation to make it happen.',
  'Please do not wait to strike until the iron is hot, but make it hot by striking.',
  'Positive thinking will let you do everything better than negative thinking will.',
  'Start today, not tomorrow. If anything, you should have started yesterday.',
  'Success is how high you bounce after you hit bottom.',
  'Success is simply a matter of luck. Ask any failure.',
  'Take risks, and you \'ll get the payoffs. Learn from your mistakes until you succeed. It \'s that simple.',
  'Teachers open the door. You enter by yourself.',
  'The art of being wise is knowing what to overlook.',
  'The best time to plant a tree is twenty years ago. The second best time is now.',
  'The biggest failure you can have in life is not trying at all.',
  'The challenge is not just to build a company that can endure but also to build one worthy of enduring.',
  'The diamond cannot be polished without friction, nor the person perfected without trials.',
  'The difference between a boss and a leader: a boss says, \'Go!\' -a leader says, \'Let\'s go!\'.',
  'The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.',
  'The fastest way to change yourself is to hang out with people who are already the way you want to be.',
  'The future belongs to those who believe in the beauty of their dreams.',
  'The mind that is anxious about future events is miserable.',
  'The more difficulties one has to encounter, within and without, the more significant and the higher in inspiration his life will be.',
  'The only journey is the one within.',
  'The only limit to our realization of tomorrow will be our doubts of today.',
  'The only people who never fail are those who never try.',
  'The only place where success comes before work is in the dictionary.',
  'The purpose is what gives life meaning.',
  'The road to success is always under construction.',
  'The secret of getting ahead is getting started.',
  'The significance of a man is not in what he attains but in what he longs to attain.',
  'The successful warrior is the average person, with laser-like focus.',
  'The venture must follow the vision. It is not enough to stare up the steps – we must step up the stairs.',
  'There is only one way to avoid criticism: Do nothing, say nothing, and be nothing.',
  'There\'s no shortage of remarkable ideas; what\'s missing is the will to execute them.',
  'To do great things is difficult, but to command great things is more complicated.',
  'To reach a port, we must sail.',
  'Try not to be a person of success, but rather try to become a person of value.',
  'Twenty years from now, you will be more disappointed by the things that you didn\'t do than by the ones you did do.',
  'User experience is everything. It always has been, but it\'s undervalued and underinvested in. If you don\'t know user-centered design, study it. Hire people who know it. Obsess over it. Live and breathe it. Get your whole company on board.',
  'Victory comes only after many struggles and countless defeats.',
  'We are what we repeatedly do. Excellence, therefore, is not an act but a habit.',
  'We can do anything we want to do if we stick to it long enough.',
  'Whatever the mind can conceive and believe, the mind can achieve.',
  'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.',
  'Whenever an individual or a business decides that success has been attained, progress stops.',
  'Whether you think you can or you can\'t, you\'re right.',
  'While a good leader sustains momentum, a great leader increases it.',
  'You may be disappointed if you fail, but you are doomed if you don\'t try.',
  'You miss 100 percent of the shots you don\'t take.',
  'You must either modify your dreams or magnify your skills.',
  'You won\'t get anything unless you have the vision to imagine it.',
  'Your most unhappy customers are your most significant source of learning.',
];